program CoopPay;
uses
  System.StartUpCopy,
  FMX.Forms,
  View.Edit.Base in 'View\Componentes\Edit\View.Edit.Base.pas' {ViewEditBase: TFrame},
  View.Edit.Codigo in 'View\Componentes\Edit\View.Edit.Codigo.pas' {ViewEditCodigo: TFrame},
  View.Edit.ComboBox in 'View\Componentes\Edit\View.Edit.ComboBox.pas' {ViewEditComboBox: TFrame},
  View.Edit.Date in 'View\Componentes\Edit\View.Edit.Date.pas' {ViewEditDate: TFrame},
  View.Edit.Icon.Right in 'View\Componentes\Edit\View.Edit.Icon.Right.pas' {ViewEditIconRight: TFrame},
  View.Edit.Pesquisa in 'View\Componentes\Edit\View.Edit.Pesquisa.pas' {ViewEditPesquisa: TFrame},
  View.Edit.Text.Area in 'View\Componentes\Edit\View.Edit.Text.Area.pas' {ViewEditTextArea: TFrame},
  View.Edit.Text in 'View\Componentes\Edit\View.Edit.Text.pas' {ViewEditText: TFrame},
  View.Edit.Time in 'View\Componentes\Edit\View.Edit.Time.pas' {ViewEditTime: TFrame},
  View.Button.Base in 'View\Componentes\Button\View.Button.Base.pas' {ViewButtonBase: TFrame},
  View.Button.Icon in 'View\Componentes\Button\View.Button.Icon.pas' {ViewButtonIcon: TFrame},
  View.Check.Basic in 'View\Componentes\Check\View.Check.Basic.pas' {ViewCheckBasic: TFrame},
  View.Check in 'View\Componentes\Check\View.Check.pas' {ViewCheck: TFrame},
  View.ComboBox.Base.Item in 'View\Componentes\ComboBox\View.ComboBox.Base.Item.pas' {ViewComboBoxBaseItem: TFrame},
  View.ComboBox.Base in 'View\Componentes\ComboBox\View.ComboBox.Base.pas',
  View.Edit.Senha in 'View\Componentes\EditSenha\View.Edit.Senha.pas' {ViewEditSenha: TFrame},
  View.List.Base in 'View\Componentes\List\View.List.Base.pas' {ViewListBase: TFrame},
  View.List.Vertical in 'View\Componentes\List\View.List.Vertical.pas' {ViewListVertical: TFrame},
  View.Modal.Base in 'View\Componentes\Modal\View.Modal.Base.pas' {ViewModalBase: TFrame},
  View.Modal.Mensagem in 'View\Componentes\ModalMensagem\View.Modal.Mensagem.pas' {ViewModalMensagem: TFrame},
  View.Base.Crud in 'View\View.Base.Crud.pas',
  View.Base in 'View\View.Base.pas' {ViewBase},
  View.MDI.Login in 'View\View.MDI.Login.pas' {ViewMDILogin},
  Helper.Scroll in 'Model\Helpers\Helper.Scroll.pas',
  Model.Utils in 'Model\Utils\Model.Utils.pas',
  Mobile.Permissions in 'Model\Utils\Mobile.Permissions.pas',
  Model.Enums in 'Model\Enums\Model.Enums.pas',
  View.Componentes.Mensagem in 'View\Componentes\View.Componentes.Mensagem.pas' {ViewComponentesMensagem: TFrame},
  View.Componentes.Censura in 'View\Componentes\View.Componentes.Censura.pas' {ViewComponentesCensura: TFrame},
  View.Componentes.Load in 'View\Componentes\View.Componentes.Load.pas' {ViewComponentesLoad: TFrame},
  Model.Static.Credencial in 'Model\Static\Model.Static.Credencial.pas',
  Model.Connection in 'Model\Connection\Model.Connection.pas' {ModelConnection: TDataModule},
  Helper.Circle in 'Model\Helpers\Helper.Circle.pas',
  Helper.Image in 'Model\Helpers\Helper.Image.pas',
  View.Step in 'View\Componentes\Step\View.Step.pas' {ViewStep: TFrame},
  Constantes.Color in 'Model\Utils\Constantes.Color.pas',
  View.Principal in 'View\View.Principal.pas' {ViewPrincipal},
  View.MDI.Principal in 'View\View.MDI.Principal.pas' {ViewMDIPrincipal},
  Frame.Categoria.Lista in 'View\Categoria\Frame.Categoria.Lista.pas' {FrameCategoriaLista: TFrame},
  View.Unidade.Medida in 'View\UnidadeMedida\View.Unidade.Medida.pas' {ViewUnidadeMedida},
  FMX.MediaLibrary.Android in 'Units\FMX.MediaLibrary.Android.pas',
  u99Permissions in 'Units\u99Permissions.pas',
  View.Cliente in 'View\Cliente\View.Cliente.pas' {ViewCliente},
  Frame.Cliente.Lista in 'View\Cliente\Frame.Cliente.Lista.pas' {FrameClienteLista: TFrame},
  View.Produto in 'View\Produto\View.Produto.pas' {ViewProduto},
  Frame.Produto.Lista in 'View\Produto\Frame.Produto.Lista.pas' {FrameProdutoLista: TFrame},
  Helper.Edit in 'Model\Helpers\Helper.Edit.pas',
  View.Pedido in 'View\Pedido\View.Pedido.pas' {ViewPedido},
  View.Selecionar.Produto.Pedido in 'View\Pedido\View.Selecionar.Produto.Pedido.pas' {ViewSelecionarProdutoPedido},
  Frame.Item.Produto.Pedido in 'View\Pedido\Frame.Item.Produto.Pedido.pas' {FrameItemProdutoPedido: TFrame},
  View.Pagamento in 'View\Pagamento\View.Pagamento.pas' {ViewPagamento},
  Frame.Item.Categoria in 'View\Pedido\Frame.Item.Categoria.pas' {FrameItemCategoria: TFrame},
  Model.Pedido.Lista in 'Model\Pedido\Model.Pedido.Lista.pas',
  Frame.Resumo.Item in 'View\Pedido\Resumo\Frame.Resumo.Item.pas' {FrameResumoItem: TFrame},
  View.Componentes.Teclado in 'View\Componentes\Teclado\View.Componentes.Teclado.pas' {FrameComponentesTeclado: TFrame},
  View.Componentes.Teclado.Quantidade in 'View\Componentes\Teclado\Quantidade\View.Componentes.Teclado.Quantidade.pas' {FrameComponentesTecladoQuantidade: TFrame},
  View.Componentes.Teclado.ValorUnitario in 'View\Componentes\Teclado\ValorUnitario\View.Componentes.Teclado.ValorUnitario.pas' {FrameComponentesTecladoValorUnitario: TFrame},
  Frame.Resumo.Opcoes in 'View\Pedido\Resumo\Frame.Resumo.Opcoes.pas' {FrameResumoOpcoes: TFrame},
  View.Componentes.Teclado.Desconto in 'View\Componentes\Teclado\Desconto\View.Componentes.Teclado.Desconto.pas' {FrameComponentesTecladoDesconto: TFrame},
  Model.Pedido.CalculoDesconto in 'Model\Pedido\Model.Pedido.CalculoDesconto.pas',
  Model.Pedido.Valores.Desconto in 'Model\Pedido\Model.Pedido.Valores.Desconto.pas',
  Frame.Resumo.Observacao in 'View\Pedido\Resumo\Frame.Resumo.Observacao.pas' {FrameResumoObservacao: TFrame},
  Frame.Resumo.Deletar.Item in 'View\Pedido\Resumo\Frame.Resumo.Deletar.Item.pas' {FrameResumoDeletarItem: TFrame},
  Model.Connection.AtualizacaoBancoDados in 'Model\Connection\Model.Connection.AtualizacaoBancoDados.pas',
  Model.Carrinho in 'Model\Carrinho\Model.Carrinho.pas',
  Model.Carrinho.Item in 'Model\Carrinho\Model.Carrinho.Item.pas',
  Model.Pedido.Dados.Item in 'Model\Pedido\Model.Pedido.Dados.Item.pas',
  View.Pagamento.Teclado.Dinheiro in 'View\Pagamento\Recebimento\View.Pagamento.Teclado.Dinheiro.pas' {FramePagamentoTecladoDinheiro: TFrame},
  Frame.Pagamento.Recebimento.Formas in 'View\Pagamento\Recebimento\Frame.Pagamento.Recebimento.Formas.pas' {FramePagamentoRecebimentoFormas: TFrame},
  Model.Pagamento.Recebimento in 'Model\Pagamento\Model.Pagamento.Recebimento.pas',
  Model.Pedido.Gerar.Pedido in 'Model\Pedido\Model.Pedido.Gerar.Pedido.pas',
  Model.Sincronizacao in 'Model\Sincronizacao\Model.Sincronizacao.pas',
  Model.Sincronizacao.Pedido in 'Model\Sincronizacao\Model.Sincronizacao.Pedido.pas',
  Model.Pagamento.Pedido in 'Model\Pagamento\Model.Pagamento.Pedido.pas',
  View.Pagamento.Teclado.Pix in 'View\Pagamento\Recebimento\View.Pagamento.Teclado.Pix.pas' {FramePagamentoTecladoPix: TFrame},
  Frame.Pagamento.Cartao in 'View\Pagamento\Recebimento\Frame.Pagamento.Cartao.pas' {FramePagamentoCartao: TFrame},
  Frame.Pagamento.Cartao.Opcoes.Parcelamento in 'View\Pagamento\Recebimento\Frame.Pagamento.Cartao.Opcoes.Parcelamento.pas' {FramePagamentoCartaoOpcoesParcelamento: TFrame},
  Frame.Pagamento.Cartao.Opcoes.Parcelamento.Item in 'View\Pagamento\Recebimento\Frame.Pagamento.Cartao.Opcoes.Parcelamento.Item.pas' {FramePagamentoCartaoOpcoesparcelamentoItem: TFrame},
  View.Pedido.Mesa in 'View\Pedido\View.Pedido.Mesa.pas' {ViewPedidoMesa},
  Frame.Pedido.Mesa in 'View\Pedido\Mesa\Frame.Pedido.Mesa.pas' {FramePedidoMesa: TFrame},
  DAO.Pedido in 'DAO\DAO.Pedido.pas',
  DAO.Base in 'DAO\DAO.Base.pas',
  Model.Records.Pedido.Mesa in 'Model\Records\Model.Records.Pedido.Mesa.pas',
  Model.Records.Categoria.Selecionada in 'Model\Records\Model.Records.Categoria.Selecionada.pas',
  Model.Records.Pagamento.Pedido in 'Model\Records\Model.Records.Pagamento.Pedido.pas',
  Model.Records.Regra.Fiscal in 'Model\Records\Model.Records.Regra.Fiscal.pas',
  Model.Records.Tipo.Pagamento in 'Model\Records\Model.Records.Tipo.Pagamento.pas',
  View.Login.Entrar in 'View\Login\View.Login.Entrar.pas' {ViewLoginEntrar},
  View.Login in 'View\Login\View.Login.pas' {ViewLogin},
  View.Recuperar.Senha in 'View\Login\View.Recuperar.Senha.pas' {ViewRecuperarSenha},
  View.Nova.Senha in 'View\Login\View.Nova.Senha.pas' {ViewNovaSenha},
  View.Verificar.Conta in 'View\Login\View.Verificar.Conta.pas' {ViewVerificarConta},
  View.Codigo.Verificacao in 'View\Login\View.Codigo.Verificacao.pas' {ViewCodigoVerificacao},
  View.Categoria in 'View\Categoria\View.Categoria.pas' {ViewCategoria},
  DAO.Pedido.Item in 'DAO\DAO.Pedido.Item.pas',
  Model.Sincronizacao.Mesa in 'Model\Sincronizacao\Model.Sincronizacao.Mesa.pas',
  Model.Records.Item.Pedido in 'Model\Records\Model.Records.Item.Pedido.pas',
  Model.Records.Item.Desconto in 'Model\Records\Model.Records.Item.Desconto.pas',
  DAO.Pedido.Pagamento in 'DAO\DAO.Pedido.Pagamento.pas',
  Service.Base in 'Services\Service.Base.pas',
  Service.Pedido.Pagamento in 'Services\Service.Pedido.Pagamento.pas',
  Service.Pedido.Item in 'Services\Service.Pedido.Item.pas',
  DAO.Carrinho.Pagamento in 'DAO\DAO.Carrinho.Pagamento.pas',
  Model.Sincronizacao.Buscar.Dados in 'Model\Sincronizacao\Model.Sincronizacao.Buscar.Dados.pas',
  Frame.Pagamento.Vendedor in 'View\Pagamento\Vendedor\Frame.Pagamento.Vendedor.pas' {FramePagamentoVendedor: TFrame},
  Frame.Pagamento.Vendedor.Item in 'View\Pagamento\Vendedor\Frame.Pagamento.Vendedor.Item.pas' {FramePagamentoVendedorItem: TFrame},
  Frame.Pagamento.Salvar.Dados in 'View\Pagamento\SalvarDados\Frame.Pagamento.Salvar.Dados.pas' {FramePagamentosSalvarDados: TFrame},
  Model.Static.Usuario in 'Model\Static\Model.Static.Usuario.pas',
  Frame.Pedido.Comanda in 'View\Pedido\Comanda\Frame.Pedido.Comanda.pas' {FramePedidoComanda: TFrame},
  View.Nova.Conta in 'View\NovaConta\View.Nova.Conta.pas' {ViewNovaConta};

{$R *.res}

begin
  // Diretivas de compilação
  // MOBILE - POS_STONE - POS_CIELO

  Application.Initialize;
  //Application.CreateForm(TViewMDILogin, ViewMDILogin);
  Application.CreateForm(TModelConnection, ModelConnection);
  Application.CreateForm(TViewLoginEntrar, ViewLoginEntrar);
  Application.Run;
end.
